### ISSUE TITLE
Test `Sanitize`d objects

### ISSUE THREAD

**Issue by mamachanko** [reconcilerio/runtime#503]
Each reconciler's `Sanitize` is called with an object before logging the value. Its feature is not control verbosity of objects in the logs, but also to redact confidential values (mostly from `Secret`). Leaking credentials to the logs should be avoided by all means. `Sanitize` is a great help for that, but it cannot easily be tested.

Maybe something like `ExpectSanitize` could be added to the reconcilers' `TestConfig` to provide test coverage for `Sanitize`.

I wonder if a hypothetical `ExpectSanitize` should be optional.

**Comment by scothis** [comment]
There's no interface that exposes the Sanitize method, it's an implementation detail of ChildReconciler and ChildSetReconciler. Your best bet is to write a pogt (plain old go test) to cover this function. Another valid approach is to wire in a custom logger to intercept what is logged and write assertions against that.

**Comment by mamachanko** [comment]
pogt. ack!
